server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ayuda-account-service-backend-db
    username: postgres
    password: postgres13240!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    web-application-type: servlet